version: '3'
services:
  imgserve:
    build: ./
    restart: unless-stopped
    container_name: ImgServe
    ports:
      - "8080:80"
    volumes:
      - /path/to/folder-you-want-to-share/:/app/Files