version: '3'
services:
  imgserve:
    build: ./
    restart: unless-stopped
    container_name: ImgServe
    ports:
      - "8080:80"
    volumes:
      - ./:/ImgServe
      - /path/to/folder-you-want-to-share/:/ImgServe/Files/